# Generated by Django 4.0.3 on 2022-03-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_name', models.CharField(max_length=35)),
                ('n_location', models.CharField(max_length=35)),
                ('n_image', models.ImageField(upload_to='n_posts/')),
                ('n_title', models.CharField(max_length=100)),
                ('n_post', models.TextField()),
                ('n_date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('n_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
