# Generated by Django 4.0.3 on 2022-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbor',
            options={'ordering': ['n_date_posted']},
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='n_image',
            field=models.ImageField(blank=True, upload_to='n_posts/'),
        ),
    ]
