# Generated by Django 4.0.3 on 2022-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_alter_neighbor_options_alter_neighbor_n_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='n_image',
            field=models.ImageField(upload_to='n_posts/'),
        ),
    ]
